PaloAltoNetworks/pan-os-python

pandevice/policies.py

Added 'negate_target' and 'target' params to policies.SecurityPolicy

implement target params for #18

---

pandevice/base.py
pandevice/objects.py
pandevice/predefined.py

Following discussion from #22 I am ready for this to be reviewed.

Predefined feature

---

pandevice/base.py

Tested with both classic and new style object types, both work fine.

Fixes PaloAltoNetworks/pandevice#40

---

examples/dyn_address_group.py

Fixing clear, list, unregister, and register operations for this script.

Fixes PaloAltoNetworks/pandevice#47 - Update dyn_address_group.py example script

---

pandevice/base.py

```from pandevice import firewall, device, network, objects
c = firewall.Firewall('10.5.174.111', 'pandevice', 'pandevice')
for num in range(3, 5):
x = network.EthernetInterface('ethernet1/{0}'.format(num), 'layer3', '{0}.{0}.{0}.1/24'.format(num))
c.add(x)
print 'creating interfaces'
c.create_type(network.EthernetInterface)
print 'ok; deleting interfaces'
c.delete_type(network.EthernetInterface)
print 'ok'
print
bulk = []
for num in range(2, 5):
x = objects.AddressObject('BulkO{0}'.format(num), '{0}.{0}.{0}.50'.format(num))
c.add(x)
bulk.append(x)
print 'creating address objects'
c.create_type(objects.AddressObject)
print 'ok; modifying objects'
objects.AddressObject.refreshall(c)
for x in c.children:
if x.uid.startswith('BulkO'):
x.description = 'SO MODIFIED' …
```

Fixes PaloAltoNetworks/pandevice#44 - add bulk operations to pandevice

---

pandevice/network.py
tests/live/test_network.py

Fixes PaloAltoNetworks/pandevice#69 - fully implements Zone

---

examples/bulk_address_objects.py
examples/bulk_subinterfaces.py
pandevice/base.py
tests/live/test_device_config.py
tests/live/test_network.py

Also added new example script, updated previous bulk example script, fixed live tests.
New script works against .25, all live tests pass.

Fixes PaloAltoNetworks/pandevice#72 - fixes and renames bulk operations

---

pandevice/base.py
pandevice/device.py
pandevice/firewall.py
pandevice/network.py
pandevice/panorama.py
tests/test_base.py

Fixes PaloAltoNetworks/pandevice#96 - Fixes PaloAltoNetworks/pandevice#84 - Fixes PaloAltoNetworks/ansible-pan#44

Fixes PaloAltoNetworks/pandevice#96 - Fixes PaloAltoNetworks/pandevice#84 - Fixes PaloAltoNetworks/ansible-pan#44

---

pandevice/policies.py

Added source_user and hip_profile docstrings

---

pandevice/policies.py

Added vartype to icmp_unreachable param

---

pandevice/device.py
pandevice/firewall.py
pandevice/objects.py
pandevice/panorama.py

Resolves enhancement request #129 .

Added CustomUrlCategory object type to objects.py

---

docs/conf.py
docs/configtree.py

Fixes issue where panorama nodes in Sphinx documentation were showing as black instead of green.  Also adds python3 compatibility for sphinx documentation.

Documentation fixes

---

pandevice/network.py

from being added to virtual router

added patch to exclude ha and aggregate-group interface

---

examples/dyn_address_group.py

Adding an additional argument to dyn_address_group.py to allow a user to specify a target vsys.

Add -s vsysN argument to allow a user to specify the vsys target

---

pandevice/ha.py
tests/test_integration.py

- Added peer-ip-backup to support HA1Backup
- Added A/A specific settings to support A/A mode
- Added link_duplex and link_speed to HA3 so it works with setup_interface, although it is not supported by API.

Ha enhancements

---

pandevice/device.py
pandevice/firewall.py
pandevice/objects.py
pandevice/userid.py

Adds dynamic user group support to pandevice

Dynamic user group support

---

HISTORY.rst
README.rst
docs/getting-started.rst
docs/howto.rst
docs/index.rst
docs/reference.rst
docs/useful-methods.rst
examples/bulk_address_objects.py
examples/bulk_subinterfaces.py

Significant update to documentation including new and reorganized content.
* Created Getting Started section with some hard-to-find intro material and general concepts
* Change Usage guide to a set of How-to Guides
* New How-to Guide for HA Pairs
* New How-to Guide for Bulk operations
* How-to Guide on Vsys now links to blog post on the topic
* New 'Useful method' section with table of all primary methods and their effects
* Many fixes and minor updates
Based on feedback from internal and external developers and the places they get stuck, documentation is now more complete and easier to consume.
Built locally using sphinx.

Documentation improvements

---

.github/workflows/ci.yml
tests/test_userid.py

Python 3.8 testing is necessary
Tested on local machine using `poetry run make test`
- Tests

test: Update tests to support python 3.8

---

panos/network.py

Adding FQDN support to IKE gateways.
Fixes #250 
Tests pass

feat: Adding FQDN support to IKE gateways

---

panos/firewall.py
panos/panorama.py

docs: Add commit normalization object docs

---

docs/getting-started.rst
panos/base.py

docs: Improve op() method documentation

---

.github/workflows/ci.yml

The current poetry github action is broken, switching to a working one.
Broken GitHub Action
Tested in this PR using GitHub Actions
CI change

ci: Change to working poetry action

---

panos/policies.py

docs: Add NAT rule dynamic translate docs

---

panos/network.py

Fixes #251 and begins work on #259.

feat: Add DHCP relay support

---

panos/base.py

fix: KeyError during Panorama commit/push

---

panos/panorama.py

Fixes #332
Fixes PaloAltoNetworks/pan-os-ansible#204

fix: PanoramaCommitAll - False args ignored

---

panos/device.py
panos/ha.py
panos/network.py
panos/objects.py
panos/policies.py
tests/test_standards.py

This also fixes a number of issues these tests found.

test: Adding new tests for class params

---

panos/userid.py

Adds ability to audit all IP addresses registered to a specific tag. This is part of the userid subsystem.

feat: Audit registered IPs for a specific tag

---

panos/__init__.py
panos/base.py
panos/firewall.py
panos/panorama.py
tests/test_init.py

feat: Add alternative quoting for `op()`

---

examples/log_forwarding_profile.py
panos/__init__.py
panos/base.py
panos/device.py
panos/firewall.py
panos/panorama.py
panos/predefined.py
tests/test_standards.py

This feature is to help users understand the various pan-os-python
object hierarchies available for a given object.

feat: Add hierarchy retrieval info

---

panos/policies.py

Added ApplicationOverride object.

feat: Added ApplicationOverride object

---

docs/getting-started.rst

docs: Document opstate namespaces

---

panos/panorama.py

feat(panos.panorama.Panorama): Add `refresh_shared_objects()`

---

panos/policies.py

Fixes issue when grabbing rulebases hitcounts from Panorama (for device-groups instead of vsys). 
Needed to get rule creation / modification timestamps for device-groups having members running PAN-OS 8 (rule creation and modification timestamps not available on the Firewall itself, but only on Panorama). 
Tested on mockup + production environment : 
- Hitcounts downloading from devices (Firewall object with vSys as PanDevice) 
- Hitcounts downloading from panorama (Panorama object as PanDevice + DeviceGroup as child) 

Add support of OPState hit_counts on Panorama / device-group rulebases

---

panos/objects.py

I have not tested, but i believe this to be an issue.
Being lazy, feel free to close for not follow instructions, but i think this is as issue.

Update tag path in ApplicationFilter

---

panos/base.py

Fixes issue #439 
Mockup environment (Panorama with pre-registered device not yet connected)

Fixes AttributeError on _set_version_and_version_info function

---

panos/objects.py

fix(panos.objects.ServiceObject): Add support for overrides

---

.readthedocs.yaml
docs/requirements.txt

ci: docs CI fix

---

panos/updater.py
tests/test_updater.py

Updating the updater logic to account for 10.2 and other historically non-standard version numbers for PAN-OS.

feat: Enhance updater logic

---

.github/workflows/ci.yml

Upgrade `setup-python` in order to fix CI for testing phase
Fixes an issue observed during automated testing of #553 
Tested in fork of this repo:
Shown above

ci: Upgrade setup-python to fix GitHub Actions test phase

---

.readthedocs.yaml

Need to regenerate docs via a patch release
Need to regenerate docs via a patch release
Locally

fix(docs): Need to regenerate docs via a patch release
