PaloAltoNetworks/pan-os-python

pandevice/policies.py

Went through the rest of the objects, didn't see any others that had `member` or `entry` vartypes that were setting `'any'` instead of `['any', ]` as the default.

Fixes PaloAltoNetworks/pandevice#34

---

pandevice/network.py

Tested with 6.1, 7.1, 8.0 EthernetInterface and Layer3Subinterface.  Verified against xml for other interfaces.

Fixes PaloAltoNetworks/pandevice#39 - adds support for DHCP settings on various data interfaces

---

pandevice/base.py
pandevice/network.py
tests/test_base.py
tests/test_integration.py

also collapses Arp class, removes Arp from tunnels and loopback interfaces, and adds some tests

Fixes PaloAltoNetworks/pandevice#60 - Allow objects to change their xpath based on the parent

---

examples/bulk_address_objects.py

When run with non-junk values, the output is the following:
```
Firewall system info: SystemInfo(version='8.0.0', platform='PA-VM', serial='015351000003333')
* There are 4 address object(s) currently *
Creating 600 address objects took: 0:00:00.456092
Bulk apply 604 address objects took: 0:00:00.477652
Creating 600 address objects took: 0:00:03.482345
Done!
```

Fixes PaloAltoNetworks/pandevice#62 - adding bulk operation example script

---

pandevice/base.py
pandevice/device.py
pandevice/firewall.py
pandevice/network.py
pandevice/panorama.py
tests/live/conftest.py
tests/live/test_device_config.py
tests/live/test_network.py
tests/live/testlib.py

Fixed parsing ParamPath.vartype == 'exist' in pandevice
ParamPath.vartype == 'exist' now has a mandatory `exist_tag`, updated pre-existing "exist" vartypes (IPv6Address was the only one with vartype='exist')
Added `device.PasswordProfile` and `device.Administrator`
Added `PanObject.request_password_hash()`
Removed invalid params from TunnelInterface, updated docstring
Fixed ordering of test case execution
Added tests for password profiles and administrators
Moved delete tests for the various testlib.Flow classes to 3rd from last
Refactored testlib.Flows a bit, added `sanity()` 
Removed sanity checking on testlib.PanoFlow and testlib.DevFlow from `cleanup_dependencies()`

Fixes PaloAltoNetworks/pandevice#38 and more

---

pandevice/base.py
pandevice/network.py
tests/live/conftest.py
tests/live/test_network.py
tests/live/testlib.py

Additionally:
* Fixes `__repr__` for devices with `self.NAME == None`
* Fixes `StaticRouteV6`
* Fixes xpath for `OspfNssaExternalRange`
* Adding `exclude=True` to `OspfNeighbor.metric` as attempting to use this results in an error
All live network tests ran against 6.1 - 8.0

Fixes PaloAltoNetworks/pandevice#56 - add live network tests

---

pandevice/base.py
pandevice/device.py
pandevice/firewall.py

```
In [1]: from pandevice import firewall, device
In [2]: c = firewall.Firewall('<snip>.25', ...)
In [3]: c.refresh_system_info()
Out[3]: SystemInfo(version='7.0.1', platform='PA-3020', serial='<snip>')
In [4]: device.Vsys.refreshall(c, name_only=True)
Out[4]: [<Vsys vsys1 0x10a31f890>, <Vsys vsys2 0x10a31fe50>, <Vsys vsys3 0x10a31ff50>]
In [5]: vsys = _[2]
In [6]: vsys.about()
Out[6]: 
{'decrypt_forwarding': None,
'display_name': None,
'dns_proxy': None,
'interface': None,
'name': 'vsys3',
'virtual_routers': None,
'virtual_wires': None,
'visible_vsys': None,
'vlans': None}
In [7]: vsys.refresh(refresh_children=False)
In [8]: vsys.about()
Out[8]: 
{'decrypt_forwarding': True,
'display_name': 'ACI-DoubleOspf-5235',
'dns_proxy': 'foo',
'interface': ['ethernet1/12.1240', …
```

Fixes PaloAltoNetworks/pandevice#70 - support limited vsys refresh

---

pandevice/base.py
pandevice/device.py
tests/test_base.py
tests/test_classic_objects.py

This also fixes classic style objects, allowing them to have a `self.NAME` of `None`, and updates the SystemSettings object to have a None name.
To make sure this change didn't cause pandevice level regressions, I've verified that the live tests for system settings still pass, and have added a few non-live tests that verify parsing.

Fixes PaloAltoNetworks/pandevice#68 - fixes equal()

---

pandevice/firewall.py
pandevice/network.py
tests/test_integration.py

Test script:
```
import pprint
from pandevice import firewall, network
def main():
c = firewall.Firewall(.25, ...)
print(c.refresh_system_info())
print('Refreshing importables...')
network.EthernetInterface.refreshall(c)
network.Vlan.refreshall(c)
network.VirtualWire.refreshall(c)
network.VirtualRouter.refreshall(c)
print('Before reorg, fw children:')
pprint.pprint(c.children)
c.organize_into_vsys()
print('After reorg, fw children:')
pprint.pprint(c.children)
if __name__ == '__main__':
main()
```
Output:
```
SystemInfo(version='7.0.1', platform='PA-3020', serial=<snip>)
Refreshing importables...
Before reorg, fw children:
[<EthernetInterface ethernet1/12 0x103b95cd0>,
<EthernetInterface ethernet1/1 0x104c1d490>,
<EthernetInterface ethernet1/16 0x104c24590>,
<EthernetInterface ethernet1/17 …
```

Fixes PaloAltoNetworks/pandevice#71 - add reorganizer and allow subinterfaces to have vsys/fw objects as parents

---

examples/dyn_address_group.py

Hi,
The example syntax that is in file dyn_address_group.py is not working as expected.
Here is an example showing the syntax in the file and the correct one:
```
[~]$ python dyn_address_group.py -l 10.24.192.10 admin password 10.6.90.18
No tags for IP: 10.6.90.18
[~]$ python dyn_address_group.py -r 10.24.192.10 admin password 10.6.90.18 test
Traceback (most recent call last):
File "dyn_address_group.py", line 130, in <module>
main()
File "dyn_address_group.py", line 97, in main
args.password,
File "/usr/local/lib/python2.7/site-packages/pandevice/base.py", line 3047, in create_from_device
system_info = device.refresh_system_info()
File "/usr/local/lib/python2.7/site-packages/pandevice/base.py", line 3455, in refresh_system_info
system_info = self.show_system_info()
File …
```

Fix dyn_address_group.py example syntax

---

pandevice/network.py

I added the next-vr value as an acceptable input type, this was tested against the panos_static_route ansible module, and appears to work appropriately.

Update to StaticRoute class to support using next-vr as a hop type

---

pandevice/base.py

Hi,
I found find_index method is not working properly.
Original codes check self.uid with name.
I think comparing child.uid and name is correct way for this method.
`
for num, child in enumerate(self.children):
if ((name is None or child.uid == name)
and type(child) == class_type):
return num
`

Fix find_index to compare child.uid with name

---

pandevice/base.py
pandevice/network.py
tests/live/test_set_reference.py

Few other updates:
* Adds a new flag, `return_boolean`, that the Ansible modules will need
* Fixes `set_vsys()` for VLANs, virtual wires, and virtual routers (only interface imports worked)

Fixes #147 - fix set_reference() with templates

---

pandevice/base.py

Updated commit method to accept an admin account name or list of admin accounts to utilize partial admin commit functionality in PanOS 8.0+.

Updated to include admin specific commit option

---

pandevice/base.py

Inherit port number when set reference in refresh mode.
When device port number is not 443, set reference in refresh mode will fail without this change.
Considering device is deployed under the NAPT, possibly device port number is not 443.
- python setup.py test
- tox
- deploy device under the NAPT and run following simple script:
```
import pandevice.firewall
import pandevice.network
fw = pandevice.firewall.Firewall('hostname', 'admin', 'password', port=14443)
eth = pandevice.network.EthernetInterface('ethernet1/1')
fw.add(eth)
eth.refresh()
eth.set_vsys('vsys1', refresh=True)
```
N/A

base: inherit port number when set reference in refresh mode

---

pandevice/__init__.py
pandevice/updater.py

When provided "latest" as target_version in `SoftwareUpdater.upgrade_to_version()`, the execution breaks because `PanOSVersion()` cannot convert the string "latest' to a proper PanOSVersion object, and the following `<` and `==` comparisons break.
Added logic in the `PanOSVersion` class `__lt__` and `__eq__` functions to always consider "latest" as higher and different, respectively, than the current version.
Also changed a couple of lines as suggested by pylint:
- Changed the exception handling of `ImportError` in `__init__` to use `str(e)` instead of `e.message`
- In `ContentUpdater`'s function `download_install()`, `self.download()` is called, but it requires only 2 arguments, not 3 (version is not an argument): removed the wrong argument

Fix support for "latest" in PanOSVersion for SoftwareUpdater

---

pandevice/device.py

New xpaths to configure Panorama servers in PAN-OS 9.1
Since PAN-OS 9.1, xpaths to configure Panorama servers have been modified.
In PAN-OS 9.1, xpaths are:
- Server 1 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama/local-panorama/panorama-server`
- Server 2 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama/local-panorama/panorama-server-2`
Below PAN-OS 9.1, xpaths are:
- Server 1 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama-server`
- Server 2 = `/config/devices/entry[@name='...']/deviceconfig/system/panorama-server-2`
```
$ flake8 pandevice tests
$ python setup.py test
$ tox
```
Then by using `panos_mgtconfig` Ansible module.
N/A
- Bug fix (non-breaking change which fixes an issue) : #196

Add panorama-server xpath for PAN-OS 9.1.0

---

pandevice/updater.py

This command adds a device reboot message after performing a device upgrade
During a device upgrade, there are no messages when the device is rebooting after an upgrade, this line adds a message post the upgrade process and before the device is going down for reboot.
There is not enough feedback from the script when a device is rebooting, especially after an upgrade, in which case, the reboot process might take some time.
Tested on my home PA-220
Tested on a local VM
Adding a reboot message.
- Breaking change (fix or feature that would cause existing functionality to change)

Adding a device reboot message after an upgrade

---

pandevice/base.py
tests/test_integration.py

also drop the element_str function of VersionPanObject since PanObject
already implemented the same function and it is inherited
This allows to use the element_str function to return pretty printed xml. The default is unchanged.
There were 2 ways to introduce this:
- Use lxml.etree which natively supports this
- Reparse the ElementTree string representation
I chose the latter because it is less intrusive in the codebase, even though it is less efficient. Note I also implemented a [migration to lxml](https://github.com/fredericve/pandevice/tree/lxml).
I'm implementing diff support in the ansible-pan project. Using pretty print is essential in showing an easily readable diff.
The test suite still runs fine with ```make test```

support pretty element string output

---

pandevice/device.py
pandevice/firewall.py
pandevice/objects.py
pandevice/panorama.py

Add support for the Region object.
name (str): Name of the region
address (list): List of IP networks
latitude (float): Latitude of the region
longitude (float): Longitude of the region
I needed to manipulate the regions in my firewall so added this pretty trivial object.
Tested against Panorama 9.0.3-h3

Add support for Regions

---

pandevice/updater.py

Fix typo in comparison for _direct_upgrade_possible() function in updater.py
Fix typo
Noticed when trying to use updater.py to upgrade from 9.0.5.xfr -> 9.1.2
#215 
- [x ] I have read the **CONTRIBUTING** document.

fix for target_version.minor in update

---

examples/log_forwarding_profile.py

Got a great question for a common use case so decided to create an example.
The use case is all firewall rules should have the same log forwarding profile.
Tested against a live PA-220 with 50 rules and multiple log forwarding profiles.
- Doc change

docs: Add example for log forwarding profiles

---

pandevice/objects.py

Added ip-wildcard as a type in the AddressObject PanObject
Closes #226 
I chose not to use a version profile for this parameter because the user will get an error on pre-9.0 versions either way. For example, there's no reason to omit the ip-wildcard on 8.1 because that AddressObject would be invalid anyway.
Support new feature in PAN-OS 9.0
Tested against PA-220

feat: Add support for wildcard address objects

---

pandevice/network.py

In network.py I removed the vartype='int' from the VersionedParamPath for the vwire 'tag-allowed' parameter.
In network.py, I removed the vartype='int' from the VersionedParamPath for the vwire 'tag-allowed' parameter. I did this because integer ranges such as 1-5 are also valid inputs
A few of our templates in Panorama had vwires with tag-allowed fields set with integer ranges which caused errors when pandevice tried to parse
I have now successfully parsed the templates in multiple environments
allows non-integer values to parse successfully in the vwire tag-allowed field, specifically integer ranges such as '1-5'

removed vartype=int from tag-allowed in network.py

---

pandevice/base.py
pandevice/firewall.py
pandevice/panorama.py

This ended up not needing to be a breaking change, so all previous scripts will still function as before.
Adding support for new commit types (each object controls what its commit `action` should be):
* `firewall.FirewallCommit`
* `panorama.PanoramaCommit`
* `panorama.PanoramaCommitAll`
Commits now look like this:
```python
fw = Firewall(...)
cmd = FirewallCommit(description="My description", admins=["admin1", "admin2"])
fw.commit(cmd=cmd, sync=True)
```
Panorama commit all's:
```python
pano = Panorama(...)
cmd = PanoramaCommitAll(
style="device group",
name="My Device Group",
description="My commit description",
devices=["serial1", "serial2"],
)
pano.commit(cmd=cmd, sync=True, sync_all=True)
cmd = PanoramaCommitAll(
style="wildfire appliance",
name="wfa1",
description="My description",
) …
```

Adding commit normalizations

---

panos/objects.py

Add missing `type` parameter to `CustomURLCategory` object
This parameter was added to PAN-OS so needs to be added to this SDK

feat: Add `type` parameter to `CustomURLCategory` object

---

panos/network.py
panos/panorama.py

Changed a leftover `pandevice` reference to `panos`
Fixes a `NameError: pandevice is not defined` exception when calling `panorama.refresh_devices` method.
Instead of said `NameError` we actually get back the list of device groups :)

Fixed typo - changed leftover pandevice to panos

---

.github/workflows/ci.yml
.releaserc.json

This makes the following significant changes to the CI Workflow.
1. Cleanup... updates names, remove unnecessary actions, etc.
2. Switch from manual install of semantic-release to a semantic-release action. This costs about 10 seconds of runtime, but gives more flexibility and has useful outputs we might use later (like for building docker images with version tags). This removes all dependency on nodejs.
3. Adds support for version release branches. For example, if 1.1.2 needs a bug fix, but develop branch already has new features, it's impossible to release a 1.1.3 with just a fix because the next version would be 1.2.0. Now, you can create a 1.1.x branch before the feature was added in develop and add the bug fix there. When the branch is pushed, it will release 1.1.3 with that fix …

ci: Clean up CI/CD workflow and use release action

---

panos/base.py
tests/test_base.py

This adds a new function to all `PanDevice` objects, `plugins()`, that returns
a list of dicts of plugin information from PAN-OS.  This function initially
only existed on Panorama, but later existed on firewall as well.
Tested against a 9.1 VM firewall and a 7.1 firewall (which doesn't support this `show` command).

feat: Add `PanDevice.plugins()`

---

panos/objects.py

PAN-OS added new tag colors a while ago (I didn't check back further than PAN-OS 8.1, and it has all these colors), and pan-os-python was missing support.
My tags needed the rich mahogany color.
Just added elements to the dictionary, didn't test against a live device.

feat: Add new tag colors

---

.github/workflows/ci.yml

Noticed this in a repository that I copy/pasted the workflow from here.  Tests were only being run on Ubuntu.
This runs tests on the different operating systems in `matrix.os`, not just `ubuntu-latest`.
Verified **Set up job** step in workflow reports different operating systems.

ci: OS wasn’t being changed from matrix

---

panos/network.py

Enabled the check box "Path Monitoring" under Virtual Router -> Static Route
This is done by adding 3 new params in the existing class StaticRoute.
Add "Path Monitoring Destination" under Virtual Router -> Static Route -> Path Monitoring
This is done by creating an new class PathMonitorDestination in network.py
Adds a new functionality.
This has been tested in a physical firewall 5220 version 9.0.10 with python 3.6
The python script that i used for the test.
fw = firewall.Firewall(HOSTNAME, USERNAME, api_key=KEY)
router = fw.add(network.VirtualRouter(name='VR2'))
static_route = {
'name': 'route2',
'destination': '1.1.1.1/32',
'nexthop_type': 'ip-address',
'nexthop': '169.254.255.103',
'enable_path_monitor': True,
'failure_condition' : 'any',
'preemptive_holdtime' : 4
}
static = …

Feature: path monitoring route

---

panos/base.py

Refers to issue https://github.com/PaloAltoNetworks/pan-os-python/issues/277

fix: PanDevice.clock: Use `datetime.datetime.strptime` instead of `datetime.strptime`

---

panos/userid.py
tests/test_userid.py

Fixes #287 - correcting attribute checked to "user" for both tag_user()
and untag_user()
New unittests have been added and pass successfully.

fix: correct user-id tag_user / untag_user

---

panos/network.py

`anti_replay` was listed as an argument twice in `IpsecTunnel`, which would override any set to `False`.
Reported as an issue in Ansible Collection.
Tested against PAN-OS 10.0.

fix: Anti-replay specified twice in IpsecTunnel

---

panos/firewall.py

Refers to issue https://github.com/PaloAltoNetworks/pan-os-python/issues/279
Parse result with unlimited number of whitespaces between 'KiB Mem :' and the next value

fix : Firewall.show_system_resources result parshing

---

panos/base.py
panos/firewall.py

Save extra information including version, content_version, and ipv6 address when doing refresh methods.
This change makes it easier to collect important information while getting the devices themselves, rather than having to make a second API call to get this information.
Tested on live devices.

Better version refresh in `refresh_system_info()` and `refresh_devices()`

---

panos/base.py
panos/policies.py
tests/test_opstate.py

Fixes #239 - Adds `opstate.get_rule_hit_count()` to both the rulebases and
to all supported rule types.

feat: Add hit count support (opstate)

---

panos/base.py
tests/test_base.py

Fixes #261 enhancement request.  This adds a convenience method that
checks users that are currently logged in to PAN-OS and returns which
user you are connected as.  This function only works on PAN-OS 10.0+.

feat: Add PanDevice.whoami()

---

panos/policies.py
tests/test_opstate.py

This adds an `audit_comment` namespace onto all rules in the
`policies` library.  Also adds a few new unittests for the XML
returned from the XML API.
Fixes #272
Fixes #209

feat: Add audit comment support for rules

---

panos/base.py
panos/panorama.py
tests/test_panorama.py

This adds knowledge and handling of device group hierarchy to
pan-os-python.
Handling of this is moved to the `opstate` namespace since device
group hierarchy is not stored in the XPATH of PAN-OS.
Note that the "async" job to update a device group's parent seems
to finish instantaneously.  Most times in my testing the job has
already finished by the time I could query the job status with
pan-os-python.

feat: Add device group hierarchy support

---

panos/base.py
panos/device.py
tests/test_device_profile_xpaths.py

This fixes #266.  The correct XPATH for profiles when directly configured
in Panorama is /config/panorama not /config/shared.  To support this, a new
object ROOT was created: PANORAMA_VSYS, which allows a fallback ROOT of VSYS,
but will otherwise be /config/panorama if the object is directly connected to
a Panorama PanDevice object.

fix: Correcting profile xpaths

---

.vscode/settings.json
panos/device.py
panos/firewall.py
panos/panorama.py
tests/test_device_profile_xpaths.py

Add new functionality Ldap server profile.
This is done by adding two new class (LdapServerProfile and LdapServer) in device.py.
adds a new functionality.
This has been tested on panorama and physical firewall 5220 on version 9.0.10 with python 3.8
below result from panorama.
```
+          config {
+            shared {
+              server-profile {
+                ldap {
+                  myldapProfil {
+                    ldap-type sun;
+                    base "DC=Mycompany, DC=Com";
+                    bind-dn user@mycompany.com;
+                    bind-password -AQ==kd/Z3bQZiv/FwZTNjObTOP3kcOI=dFNrnYwFGIWTS1aV4NWRaQ==;
+                    bind-timelimit 30;
+                    timelimit 30;
+                    retry-interval 70;
+                    ssl yes;
+ …
```

feature Ldap server profile

---

panos/device.py

Signed-off-by: Stephen Steiner <ssteiner@paloaltonetworks.com>
Adding `protocol` attribute to the `EmailServer` class in `panos.device` to support the changes in PanOS 10+
Since the introduction of PanOS 10, the email server configuration requires the protocol attribute as either SMTP or TLS
Ran `poetry run make test`
Ran `poetry run make test-all` (Failed, but for other than changes made)

#347 - Adding protocol to EmailServer class

---

panos/__init__.py

Warning produced when running on end-of-life python version:
```
>>> import panos
panos/__init__.py:44: RuntimeWarning: pan-os-python - Running on end-of-life Python version (2.7.18). This Python version is not supported and might cause problems. Please upgrade to Python 3.6 or higher.
RuntimeWarning,
```
closes #341

chore: Add warning when on EOL python

---

panos/device.py
panos/firewall.py
panos/objects.py
panos/panorama.py

Add new functionality log settings on system and config.
This is done by adding two new class (LogSettingsSystem and LogSettingsConfig) in device.py.
adds a new functionality.
This has been tested on panorama and physical firewall 5220 on version 9.0.10 with python 3.8
below result from panorama.
```
templates tmpl-common-test;
+          config {
+            shared {
+              log-settings {
+                email {
+                  email_profil {
+                    server {
+                      1.1.1.1 {
+                        display-name myname;
+                        gateway 1.1.1.1;
+                        from myname@name.com;
+                        to tomyname@myname.com;
+                      }
+                    }
+                  }
+                }
+ …
```

add feat logsettings system and config

---

panos/policies.py

feat: Add new HIP options to security rules

---

panos/ha.py
tests/test_integration.py

> Note: Merge with "Rebase and Merge", not squash.
Removes some HA interface stubs and assigns no 'name' to the HA interface class. This fixes 2 issues:
Issue 1: HA interfaces created with args, instead of kwargs, were not getting the correct IP address because pan-os-python expected the first arg to be a name.
Issue 2: #350 - HA interface stubs were created in the HighAvailability instance, but some newer models of VM-Series do not have these interfaces (eg. ha1-backup), so the stub caused an error.
Tested on VM-Series that supports ha1-backup and VM-Series that does not support ha1-backup. Works on both.

fix: Remove legacy HA interface stubs

---

panos/policies.py

PAN-OS 9.0+ added a new group-tag field to all policy rules, so this is
to bring pan-os-python up-to-par with this addition.
Fixes #248

feat: Add group_tag to all policy rules

---

.github/workflows/ci.yml

See the following for more information:
https://github.com/actions/virtual-environments/issues/4060

ci: Remove python 3.6

---

panos/userid.py
tests/test_userid.py

Ben Parker  2:39 PM
So this call should actaully support another argument [https://pan-os-python.readthedocs.io/en/latest/module-userid.html#panos.userid.UserId.audit_registered_ip](https://pan-os-python.readthedocs.io/en/latest/module-userid.html#panos.userid.UserId.audit_registered_ip])
the timeout like argument like [https://pan-os-python.readthedocs.io/en/latest/module-userid.html#panos.userid.UserId.audit_registered_ip](https://pan-os-python.readthedocs.io/en/latest/module-userid.html#panos.userid.UserId.audit_registered_ip)
Ben Parker  2:40 PM
Here is what the whole API call looks like 
```
https://{{host}}/api?key={{key}}&type=user-id&cmd=<uid-message><version>2.0</version><type>update</type><payload><register><entry ip="{{tagged-ip}}"><tag><member …
```

add optional timeout for userid register()

---

panos/base.py
tests/test_params.py

This fixes "attrib" style params, which are (currently) only present in
the various rule objects in policies.py.
Doing `rule.apply()` when the uuid is set and the name is unchanged
does not cause PAN-OS to complain, so this fix does not cause any
regressions / change in standard behavior.
Doing `rule.apply() when the uuid is set and the name IS changed
causes PAN-OS to silently create another rule with a new uuid.  This
of course means that the uuid of the object that was applied differs
between the user's object hierarchy and what's on live.
In light of this, we might want to investigate how to handle changing the
unique identifier from the name to the uuid of the rule, but some research
is needed on if this is actually possible from an XPATH perspective as well
as how to gracefully …

fix: Fixes `refresh()` for attrib style params

---

panos/policies.py
tests/test_standards.py

DecryptionRule _setup method was referencing wrong xpath for decryption rules.
It fixes correctly parsing DecryptionRule objects.

bug: DecryptionRule wrong xpath.

---

panos/base.py
panos/panorama.py
panos/policies.py
tests/test_opstate.py
tests/test_standards.py

This condenses the opstate namespace into its own class, and adds
an `.about()`.  This means that `.opstate` will always exist
(as opposed to just if there are functions there or not).
Work on #396

feat: Make opstate more discoverable for users

---

panos/policies.py

Added policies.AuthenticationRule class to be able to retrieve / update authentication rules. 
This rulebase was not available yet on the tool. 
Tested on production PaloAlto / Panorama deployment. 
N/A

Added policies.AuthenticationRule

---

panos/__init__.py
panos/base.py
tests/test_base.py
tests/test_init.py

Some testing of PAN-OS responsiveness has lead to the discovery that
a `delete()` API call of around 25k characters can take anywhere
from 3.3sec to 15sec, depending on the load.  All pan-os-python API
calls are expected to complete within 30sec by default.  If the API
call takes longer than that to complete, then the call times out
and the delete doesn't seem to take.
Thus, `delete_similar()` will now break deletes into chunks of
around 25k characters.

fix: `delete_similar()` now breaks delete calls into chunks

---

panos/base.py
tests/test_base.py

fix(panos.base.PanObject.refresh_variable): Refresh works again for regular and attrib style params

---

panos/device.py

fix(panos.device.SystemSettings): Add support for proxy config

---

panos/updater.py

The command triggered in `SoftwareUpdater.install()` method has wrong formatting around `load_config` parameter. All non key words should be quoted, this includes the value of `load_config` ([see `op` method documentation](https://github.com/PaloAltoNetworks/pan-os-python/blob/20dd7b7ecd710b824a97416f849d6084436ef57f/panos/base.py#L4018-L4020)).
For the moment the `load_config` parameter is not quoted which causes the `op` method to fail.
W/o this fix running an upgrade with named configuration load after reboot is not possible.
This fix was used in an Ansible playbook.

Fix formatting of `request system software install` command - load_config parameter

---

panos/panorama.py

Adding support for the [PAN-OS 10.2 feature](https://docs.paloaltonetworks.com/pan-os/10-2/pan-os-release-notes/features-introduced-in-pan-os/panorama-features) of Administrator-Level Push from Panorama to Managed Devices
Motivation is adding support for a new PAN-OS feature, and also to support adding this feature in pan-os-ansible ([ref](https://github.com/PaloAltoNetworks/pan-os-ansible/issues/361))
Tested locally, with Panorama 11.0.0 and managed firewall 10.2.3
```
panorama = Panorama(HOSTNAME, USERNAME, PASSWORD)
cmd = PanoramaCommitAll(
style="device group",
name="poc-dg",
include_template=False,
force_template_values=False,
admins=["other"],
)
sync = False
sync_all = True
result = panorama.commit(cmd=cmd, sync=sync, sync_all=sync_all)
```
- New feature (non-breaking change which …

Add admins parameter to Panorama push

---

Makefile
poetry.lock
pyproject.toml

dephell is no longer being maintained. dephell uses pyproject.toml to generate a setup.py file for pip to install the package. Long term this shouldn't matter because recent versions of pip can now install packages using pyproject.toml and don't care about setup.py.
However, there may be users who leverage pan-os-python in environments that don't use newer versions of pip, especially since we deprecated but haven't completely removed python 2.7 and 3.5 support.
Next steps after this PR:
1. remove support for EOL python versions
2. eliminate poetry2setup and setup.py
3. ensure pyproject.toml has the necessary `[build-system]` configuration to be installed by pip
4. do a major release of pan-os-python, since removing support for python versions is a breaking change

build: Replace dephell with poetry2setup

---

panos/network.py

In PAN-OS, layer 2 interfaces do not get added to virtual routers. This fix stops the SDK trying to add layer 2 interfaces to virtual routers when the interface is created.
Fix for https://github.com/PaloAltoNetworks/pan-os-ansible/issues/173
Tested locally via Ansible
Before:
```
TASK [Create interfaces] ***********************************************************************************************************************************************************************************************************************
failed: [host_labfw] (item={'name': 'ethernet1/8', 'mode': 'layer2', 'vlan_name': 'Management', 'lldp_enabled': False, 'zone_name': 'VLANs'}) => {"ansible_loop_var": "item", "changed": false, "item": {"lldp_enabled": false, "mode": "layer2", "name": "ethernet1/8", …
```

fix: layer2 interface creation

---

.github/workflows/ci.yml

Update Ubuntu runner version for release process
Needed because 18.04 is now unsupported (https://github.com/actions/runner-images/issues/6002 & https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
N/A
N/A
- CI

ci: Update Ubuntu runner version

---

panos/device.py

Add the option for HTTP Server Profiles to key off Decrypt and GP logs.
Decrypt and GP logs were added in PAN-OS 10.0 and 9.1 respectively.
This feature coverage is also useful for upcoming Event-Driven Ansible operations.
Tested locally with Ansible ([playbook](https://github.com/jamesholland-uk/playground/blob/main/pan-os-ansible/http-server-profiles.yml))

feat: Decrypt and GP for HTTP server profiles

---

panos/objects.py

Add decryption log-type to log forwarding
Decryption logs were added in PAN-OS 10.0
Tested locally with Ansible
Before:
After:

feat: Add decryption log-type to log forwarding

---

panos/network.py

Fixes #534 
In at least as early as 9.1, the 'append community' action within BGP is a member list which was causing BGP updates to fail when attempting to update an existing BGP protocol element with this configured.
All that has changed is the vartype of "action_community_argument" to be "member". 
Example XML from 9.1 for this path;
```xml
<response status="success" code="19">
<result total-count="1" count="1">
<append admin="panadmin" dirtyId="12" time="2023/11/21 11:36:45">
<member admin="panadmin" dirtyId="12" time="2023/11/21 11:36:45">local-as</member>
</append>
</result>
</response>
```

Fix action_community_argument vartype

---

panos/base.py

Adding an exception handler to catch datatype errors with jobs where details is None.  
Resolve bug described in #470
The command that encountered the issue were rerun and the response was successful. 
``` python
download_cmd = "<request><plugins><download><file>vm_series-2.1.2</file></download></plugins></request>"
download_response = parent.op(download_cmd, cmd_xml=False)
download_result = parent.syncjob(download_response)
```
Successful download response
``` json
{
"success":true,
"result":"OK",
"jobid":"18",
"user":"None",
"warnings":"None",
"starttime":"2022/07/26 08:58:18",
"endtime":"08:58:19",
"messages":[
],
"devices":{
},
"xml":"<Element""response"at 0x7f68569ca180>
}
```
Tested against panos 9.1 using the pan-os-python poetry venv. 
This is very small and self contained change …

Fix for None datatype in _parse_job_results()

---

panos/device.py

This simple misspelling causes the creation of AuthenticationProfile objects to fail
```
PanXapiError:  authentication-profile -> MyRADIUS -> locakout unexpected here
````

incorrect path name fix

---

panos/base.py

Attempting to handle "push" to Log Collector Groups (LCG)
Attempting to close #487 
XML API response from a push to a DG, for example, returns a job ID etc:
<response status="success" code="19">
<result>
<msg>
<line>Job enqueued with jobid 16892</line>
</msg>
<job>16892</job>
</result>
</response>
XML API response from a push to a LCG looks totally different:
<response status="success">
<msg>
<line>Generated config and committed to connected collectors in group log-coll-grp</line>
</msg>
</response>
- There does not appear to be an ID against which to track the progress, status or success/failure of the push.
- The lack of `<result>` in the LCG response broke the Ansible module.
- The fixes proposed work, but may not be the best way to handle LCG pushes.
Tested locally. Both native Python …

Handling Log Collector Group (LCG) pushes

---

.readthedocs.yaml
docs/conf.py

Fixes ReadTheDocs issues that have cropped up over time

build: fix readthedocs visuals

---

docs/module-base.rst
docs/module-device.rst
docs/module-errors.rst
docs/module-firewall.rst
docs/module-ha.rst
docs/module-network.rst
docs/module-objects.rst
docs/module-panorama.rst
docs/module-plugins.rst
docs/module-policies.rst
docs/module-predefined.rst
docs/module-updater.rst
docs/module-userid.rst

Added ":members:" to module-*.rst files.
The current documentation is missing the docstrings from the classes in the modules, it shows only the docstring from the module itself which is not useful for the module users.
I run "make docs" for Sphinx to crate the docs and verified that the docstrings are now populated.
This is what the current documentation shows:
This is what it will show with the changes:

add members to automodule for Sphinx to pickup docstrings

---

panos/base.py

Issue described in #581.
Closes #581.
1. poetry run make test
2. Integration tests incl. Commit and Commit-All performed in the lab.

fix(panos/base): Allow missing `tfin` attribute in Commit-All result from a device

---

.github/workflows/ci.yml

GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also includes:
- Updates from `actions/cache` `v1` -> `v4` due to https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
- Updates from `actions/setup-python` `v2` -> `v5` so that the build runs

Pin GitHub Actions

---

.github/workflows/ci.yml
.readthedocs.yaml
docs/conf.py
docs/module-base.rst
docs/module-device.rst
docs/module-errors.rst
docs/module-firewall.rst
docs/module-ha.rst
docs/module-network.rst
docs/module-objects.rst
docs/module-panorama.rst
docs/module-plugins.rst
docs/module-policies.rst
docs/module-predefined.rst
docs/module-updater.rst
docs/module-userid.rst
panos/base.py

1.12.2 release

---

panos/base.py

With latest develop/master branch commit (not yet released) - there was an issue committing to Panorama which has no changes to commit (discovered when running the `panos_commit_panorama` ansible module).
Simple python script to test the issue:
from panos.panorama import Panorama, PanoramaCommitAll, PanoramaCommit
```python
panorama = Panorama("<YOUR_IP>", "<YOUR_USERNAME>", "<YOUR_PASSWORD>")
cmd = PanoramaCommit()
sync = True
result = panorama.commit(cmd=cmd, sync=sync)
print(result)
```
Result:
```bash
python3 python_test_panorama.py
Traceback (most recent call last):
File "/Users/hgunica/Documents/PROJECTS/kyndryl/pso-azure-kyndryl-1089022/kx-panw-cac/ansible/panorama-cac/.venv/lib/python3.11/site-packages/panos/base.py", line 4899, in _commit
jobid = …
```

fix(panos/base): Added check for `commit_response` text validation

---

panos/base.py
panos/network.py

Bugfix release
